"""
Zyrstar Proprietary AI Detection Engine
----------------------------------------
Entirely self-contained: no third-party AI-detection API calls. Estimates
the probability that a text was AI-generated by combining eight
independent linguistic signals into a weighted composite score. Every
signal is computed from classical NLP / statistics (n-gram frequency,
sentence-length distribution, lexical diversity, cosine similarity of
TF-IDF sentence vectors, POS-pattern entropy) so the whole pipeline runs
comfortably on a CPU-only host.

Signals
-------
1. Perplexity proxy       - avg. corpus rarity of words (low perplexity /
                             very "expected" word choice correlates with
                             LLM output, which favors high-probability
                             tokens).
2. Burstiness              - human writing has high variance in sentence
                             length and rare-word usage ("bursty");
                             AI text tends to be flatter/more uniform.
3. Semantic similarity     - average pairwise cosine similarity between
                             consecutive sentences (TF-IDF). AI text is
                             often more locally coherent/uniform than
                             human tangents.
4. Sentence structure var. - coefficient of variation of sentence length
                             and POS-tag start patterns.
5. Vocabulary diversity    - type-token ratio / MTLD-style measure.
6. Repetition               - n-gram repetition rate.
7. Coherence consistency   - variance of TF-IDF similarity across the
                             whole document (too-consistent = synthetic).
8. AI boilerplate phrases  - presence of stock LLM transition phrases.

The final score is a calibrated weighted sum, clipped to [0, 100].
"""
from __future__ import annotations

import math
import re
from collections import Counter
from dataclasses import dataclass

import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

from app.services.nlp_utils import (
    contains_ai_boilerplate,
    split_sentences,
    tokenize_words,
    word_zipf,
)


@dataclass
class Metric:
    name: str
    label: str
    score: float  # 0-100, higher = more "AI-like" for this signal
    description: str


class DetectionEngine:
    WEIGHTS = {
        "perplexity": 0.20,
        "burstiness": 0.18,
        "semantic_similarity": 0.12,
        "structure_variation": 0.15,
        "vocabulary_diversity": 0.13,
        "repetition": 0.12,
        "coherence": 0.06,
        "boilerplate": 0.04,
    }

    def analyze(self, text: str) -> dict:
        sentences = split_sentences(text)
        words = tokenize_words(text)

        if len(words) < 8 or len(sentences) < 1:
            return self._short_text_result(text, sentences, words)

        metrics: list[Metric] = [
            self._perplexity_proxy(words),
            self._burstiness(sentences),
            self._semantic_similarity(sentences),
            self._structure_variation(sentences),
            self._vocabulary_diversity(words),
            self._repetition(words),
            self._coherence(sentences),
            self._boilerplate(text),
        ]

        composite = sum(m.score * self.WEIGHTS[m.name] for m in metrics)
        composite = float(np.clip(composite, 0, 100))

        verdict, confidence = self._verdict(composite)

        return {
            "ai_probability": round(composite, 1),
            "verdict": verdict,
            "confidence": confidence,
            "metrics": [
                {
                    "name": m.name,
                    "label": m.label,
                    "score": round(m.score, 1),
                    "description": m.description,
                }
                for m in metrics
            ],
            "word_count": len(words),
            "sentence_count": len(sentences),
        }

    # ------------------------------------------------------------------
    # Individual signals
    # ------------------------------------------------------------------

    def _perplexity_proxy(self, words: list[str]) -> Metric:
        """Average word rarity (inverse of Zipf frequency). LLMs skew toward
        common, high-probability tokens -> lower average rarity -> flag
        as more AI-like when rarity is unusually low AND uniform."""
        zipfs = [word_zipf(w) for w in words if len(w) > 1]
        if not zipfs:
            return Metric("perplexity", "Perplexity", 50.0, "Insufficient vocabulary to assess.")

        avg_zipf = float(np.mean(zipfs))
        std_zipf = float(np.std(zipfs))

        # High avg frequency (common words) + low variance -> AI-like.
        commonness_score = np.clip((avg_zipf - 3.0) / 3.0, 0, 1) * 100
        uniformity_penalty = np.clip((1.5 - std_zipf) / 1.5, 0, 1) * 100
        score = 0.6 * commonness_score + 0.4 * uniformity_penalty

        return Metric(
            "perplexity",
            "Perplexity",
            float(np.clip(score, 0, 100)),
            "Measures how predictable/common the word choices are. "
            "AI text tends to favor frequent, high-probability words.",
        )

    def _burstiness(self, sentences: list[str]) -> Metric:
        lengths = [len(tokenize_words(s)) for s in sentences]
        if len(lengths) < 2:
            return Metric("burstiness", "Burstiness", 50.0, "Too few sentences to measure variance.")

        mean_len = float(np.mean(lengths))
        std_len = float(np.std(lengths))
        burstiness_index = (std_len - mean_len) / (std_len + mean_len + 1e-6)
        # Human text: burstiness_index closer to 0 or positive (high variance).
        # AI text: often negative (very uniform sentence lengths).
        score = np.clip((0.15 - burstiness_index) / 0.5, 0, 1) * 100

        return Metric(
            "burstiness",
            "Burstiness",
            float(score),
            "Human writing varies sentence length unevenly (bursty); "
            "AI text often produces uniformly-paced sentences.",
        )

    def _semantic_similarity(self, sentences: list[str]) -> Metric:
        if len(sentences) < 3:
            return Metric("semantic_similarity", "Semantic Flow", 40.0, "Too short to assess sentence-to-sentence flow.")

        try:
            vectorizer = TfidfVectorizer(stop_words="english")
            matrix = vectorizer.fit_transform(sentences)
            sims = []
            for i in range(len(sentences) - 1):
                sim = cosine_similarity(matrix[i], matrix[i + 1])[0][0]
                sims.append(sim)
            avg_sim = float(np.mean(sims)) if sims else 0.0
        except ValueError:
            avg_sim = 0.0

        # Very high consecutive-sentence similarity -> overly consistent -> AI-like.
        score = np.clip((avg_sim - 0.08) / 0.35, 0, 1) * 100

        return Metric(
            "semantic_similarity",
            "Semantic Flow",
            float(score),
            "Consecutive-sentence topical similarity. Unnaturally smooth "
            "transitions can indicate synthetic generation.",
        )

    def _structure_variation(self, sentences: list[str]) -> Metric:
        lengths = [len(tokenize_words(s)) for s in sentences]
        openers = [tokenize_words(s)[0].lower() if tokenize_words(s) else "" for s in sentences]

        if len(lengths) < 2:
            return Metric("structure_variation", "Structural Variation", 50.0, "Too few sentences to assess.")

        cv = float(np.std(lengths) / (np.mean(lengths) + 1e-6))
        opener_diversity = len(set(openers)) / max(len(openers), 1)

        # Low coefficient of variation + low opener diversity -> AI-like.
        uniformity_score = np.clip((0.55 - cv) / 0.55, 0, 1) * 100
        repetitive_openers_score = np.clip((0.6 - opener_diversity) / 0.6, 0, 1) * 100
        score = 0.6 * uniformity_score + 0.4 * repetitive_openers_score

        return Metric(
            "structure_variation",
            "Structural Variation",
            float(np.clip(score, 0, 100)),
            "Checks variety in sentence length and sentence openers. "
            "Repetitive structure is a common AI-generation fingerprint.",
        )

    def _vocabulary_diversity(self, words: list[str]) -> Metric:
        lowered = [w.lower() for w in words]
        if len(lowered) < 10:
            return Metric("vocabulary_diversity", "Vocabulary Diversity", 50.0, "Too short to assess lexical range.")

        ttr = len(set(lowered)) / len(lowered)
        # MTLD-lite: sliding window TTR to reduce length-bias.
        window = 50
        window_ttrs = []
        for i in range(0, max(len(lowered) - window, 1), window):
            chunk = lowered[i : i + window]
            if chunk:
                window_ttrs.append(len(set(chunk)) / len(chunk))
        mtld_like = float(np.mean(window_ttrs)) if window_ttrs else ttr

        # Low diversity -> AI-like (LLMs often reuse a narrower working vocabulary).
        score = np.clip((0.62 - mtld_like) / 0.35, 0, 1) * 100

        return Metric(
            "vocabulary_diversity",
            "Vocabulary Diversity",
            float(score),
            "Ratio of unique words to total words. Narrow, repetitive "
            "vocabulary is common in AI-generated text.",
        )

    def _repetition(self, words: list[str]) -> Metric:
        lowered = [w.lower() for w in words]
        if len(lowered) < 6:
            return Metric("repetition", "N-gram Repetition", 30.0, "Too short to assess repetition.")

        bigrams = list(zip(lowered, lowered[1:]))
        trigrams = list(zip(lowered, lowered[1:], lowered[2:]))

        bigram_counts = Counter(bigrams)
        trigram_counts = Counter(trigrams)

        repeated_bigrams = sum(1 for c in bigram_counts.values() if c > 1)
        repeated_trigrams = sum(1 for c in trigram_counts.values() if c > 1)

        bigram_rep_rate = repeated_bigrams / max(len(bigrams), 1)
        trigram_rep_rate = repeated_trigrams / max(len(trigrams), 1)

        score = np.clip((0.6 * bigram_rep_rate + 0.4 * trigram_rep_rate) / 0.15, 0, 1) * 100

        return Metric(
            "repetition",
            "N-gram Repetition",
            float(score),
            "Detects repeated phrase patterns (bigrams/trigrams) across the text.",
        )

    def _coherence(self, sentences: list[str]) -> Metric:
        if len(sentences) < 4:
            return Metric("coherence", "Coherence Consistency", 40.0, "Too short to assess document-level coherence.")

        try:
            vectorizer = TfidfVectorizer(stop_words="english")
            matrix = vectorizer.fit_transform(sentences)
            sim_matrix = cosine_similarity(matrix)
            n = sim_matrix.shape[0]
            upper = sim_matrix[np.triu_indices(n, k=1)]
            variance = float(np.var(upper)) if upper.size else 0.0
        except ValueError:
            variance = 0.02

        # Very low variance in pairwise similarity across the whole doc ->
        # unnaturally consistent -> AI-like.
        score = np.clip((0.02 - variance) / 0.02, 0, 1) * 100

        return Metric(
            "coherence",
            "Coherence Consistency",
            float(score),
            "Measures whether topical coherence stays suspiciously constant "
            "throughout the entire document.",
        )

    def _boilerplate(self, text: str) -> Metric:
        hits = contains_ai_boilerplate(text)
        score = min(len(hits) * 18, 100)
        found_suffix = ""
        if hits:
            joined = ", ".join(hits[:5])
            found_suffix = f" (found: {joined})"
        return Metric(
            "boilerplate",
            "AI Phrase Patterns",
            float(score),
            "Flags stock transition phrases disproportionately common in "
            f"LLM output{found_suffix}.",
        )

    def _short_text_result(self, text: str, sentences: list[str], words: list[str]) -> dict:
        return {
            "ai_probability": 0.0,
            "verdict": "Insufficient text",
            "confidence": "low",
            "metrics": [],
            "word_count": len(words),
            "sentence_count": len(sentences),
        }

    def _verdict(self, score: float) -> tuple[str, str]:
        if score < 20:
            return "Likely Human-Written", "high"
        if score < 40:
            return "Probably Human-Written", "medium"
        if score < 60:
            return "Mixed Signals", "low"
        if score < 80:
            return "Probably AI-Generated", "medium"
        return "Likely AI-Generated", "high"


detection_engine = DetectionEngine()
